-- 브랜드 데이터 삽입
INSERT INTO brand (name)
VALUES ('A'),
       ('B'),
       ('C'),
       ('D'),
       ('E'),
       ('F'),
       ('G'),
       ('H'),
       ('I');

-- 제품 데이터 삽입 (category, brand, price)
INSERT INTO product (category, brand_id, price)
VALUES ('상의', (SELECT id FROM brand WHERE name = 'A'), 11200),
       ('아우터', (SELECT id FROM brand WHERE name = 'A'), 5500),
       ('바지', (SELECT id FROM brand WHERE name = 'A'), 4200),
       ('스니커즈', (SELECT id FROM brand WHERE name = 'A'), 9000),
       ('가방', (SELECT id FROM brand WHERE name = 'A'), 2000),
       ('모자', (SELECT id FROM brand WHERE name = 'A'), 1700),
       ('양말', (SELECT id FROM brand WHERE name = 'A'), 1800),
       ('액세서리', (SELECT id FROM brand WHERE name = 'A'), 2300),

       ('상의', (SELECT id FROM brand WHERE name = 'B'), 10500),
       ('아우터', (SELECT id FROM brand WHERE name = 'B'), 5900),
       ('바지', (SELECT id FROM brand WHERE name = 'B'), 3800),
       ('스니커즈', (SELECT id FROM brand WHERE name = 'B'), 9100),
       ('가방', (SELECT id FROM brand WHERE name = 'B'), 2100),
       ('모자', (SELECT id FROM brand WHERE name = 'B'), 2000),
       ('양말', (SELECT id FROM brand WHERE name = 'B'), 2000),
       ('액세서리', (SELECT id FROM brand WHERE name = 'B'), 2200),

       ('상의', (SELECT id FROM brand WHERE name = 'C'), 10000),
       ('아우터', (SELECT id FROM brand WHERE name = 'C'), 6200),
       ('바지', (SELECT id FROM brand WHERE name = 'C'), 3300),
       ('스니커즈', (SELECT id FROM brand WHERE name = 'C'), 9200),
       ('가방', (SELECT id FROM brand WHERE name = 'C'), 2200),
       ('모자', (SELECT id FROM brand WHERE name = 'C'), 1900),
       ('양말', (SELECT id FROM brand WHERE name = 'C'), 2200),
       ('액세서리', (SELECT id FROM brand WHERE name = 'C'), 2100),

       ('상의', (SELECT id FROM brand WHERE name = 'D'), 10100),
       ('아우터', (SELECT id FROM brand WHERE name = 'D'), 5100),
       ('바지', (SELECT id FROM brand WHERE name = 'D'), 3000),
       ('스니커즈', (SELECT id FROM brand WHERE name = 'D'), 9500),
       ('가방', (SELECT id FROM brand WHERE name = 'D'), 2500),
       ('모자', (SELECT id FROM brand WHERE name = 'D'), 1500),
       ('양말', (SELECT id FROM brand WHERE name = 'D'), 2400),
       ('액세서리', (SELECT id FROM brand WHERE name = 'D'), 2000),

       ('상의', (SELECT id FROM brand WHERE name = 'E'), 10700),
       ('아우터', (SELECT id FROM brand WHERE name = 'E'), 5000),
       ('바지', (SELECT id FROM brand WHERE name = 'E'), 3800),
       ('스니커즈', (SELECT id FROM brand WHERE name = 'E'), 9900),
       ('가방', (SELECT id FROM brand WHERE name = 'E'), 2300),
       ('모자', (SELECT id FROM brand WHERE name = 'E'), 1800),
       ('양말', (SELECT id FROM brand WHERE name = 'E'), 2100),
       ('액세서리', (SELECT id FROM brand WHERE name = 'E'), 2100),

       ('상의', (SELECT id FROM brand WHERE name = 'F'), 11200),
       ('아우터', (SELECT id FROM brand WHERE name = 'F'), 7200),
       ('바지', (SELECT id FROM brand WHERE name = 'F'), 4000),
       ('스니커즈', (SELECT id FROM brand WHERE name = 'F'), 9300),
       ('가방', (SELECT id FROM brand WHERE name = 'F'), 2100),
       ('모자', (SELECT id FROM brand WHERE name = 'F'), 1600),
       ('양말', (SELECT id FROM brand WHERE name = 'F'), 2300),
       ('액세서리', (SELECT id FROM brand WHERE name = 'F'), 1900),

       ('상의', (SELECT id FROM brand WHERE name = 'G'), 10500),
       ('아우터', (SELECT id FROM brand WHERE name = 'G'), 5800),
       ('바지', (SELECT id FROM brand WHERE name = 'G'), 3900),
       ('스니커즈', (SELECT id FROM brand WHERE name = 'G'), 9000),
       ('가방', (SELECT id FROM brand WHERE name = 'G'), 2200),
       ('모자', (SELECT id FROM brand WHERE name = 'G'), 1700),
       ('양말', (SELECT id FROM brand WHERE name = 'G'), 2100),
       ('액세서리', (SELECT id FROM brand WHERE name = 'G'), 2000),

       ('상의', (SELECT id FROM brand WHERE name = 'H'), 10800),
       ('아우터', (SELECT id FROM brand WHERE name = 'H'), 6300),
       ('바지', (SELECT id FROM brand WHERE name = 'H'), 3100),
       ('스니커즈', (SELECT id FROM brand WHERE name = 'H'), 9700),
       ('가방', (SELECT id FROM brand WHERE name = 'H'), 2100),
       ('모자', (SELECT id FROM brand WHERE name = 'H'), 1600),
       ('양말', (SELECT id FROM brand WHERE name = 'H'), 2000),
       ('액세서리', (SELECT id FROM brand WHERE name = 'H'), 2000),

       ('상의', (SELECT id FROM brand WHERE name = 'I'), 11400),
       ('아우터', (SELECT id FROM brand WHERE name = 'I'), 6700),
       ('바지', (SELECT id FROM brand WHERE name = 'I'), 3200),
       ('스니커즈', (SELECT id FROM brand WHERE name = 'I'), 9500),
       ('가방', (SELECT id FROM brand WHERE name = 'I'), 2400),
       ('모자', (SELECT id FROM brand WHERE name = 'I'), 1700),
       ('양말', (SELECT id FROM brand WHERE name = 'I'), 1700),
       ('액세서리', (SELECT id FROM brand WHERE name = 'I'), 2400);
